#!/usr/bin/env python3
"""Generate DASHBOARD.md from feature directories.

Scans docs/features/*/ to find all features and their status based on file presence:
- idea.md only → backlog
- idea.md + plan.md → in-progress
- idea.md + plan.md + shipped.md → completed

Usage:
    python3 dashboard.py <project_root>

Can also be imported and called as a library:
    from dashboard import generate_dashboard
    generate_dashboard(project_root)
"""

import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

from .models import FeatureContext, FeatureStatus


def generate_dashboard(project_root: Path) -> None:
    """Generate DASHBOARD.md from feature directories.

    Args:
        project_root: Path to the project root directory
    """
    features_dir = project_root / "docs" / "features"
    dashboard_path = features_dir / "DASHBOARD.md"

    # Ensure features directory exists
    features_dir.mkdir(parents=True, exist_ok=True)

    # Collect features by status
    backlog_items: list[FeatureContext] = []
    inprogress_items: list[FeatureContext] = []
    completed_items: list[FeatureContext] = []

    # Scan feature directories
    if features_dir.exists():
        for feature_dir in sorted(features_dir.iterdir()):
            # Skip non-directories and DASHBOARD.md
            if not feature_dir.is_dir():
                continue
            if feature_dir.name == "DASHBOARD.md":
                continue

            # Parse feature context
            ctx = FeatureContext.from_directory(feature_dir)
            if ctx is None:
                continue

            # Categorize by status
            if ctx.status == FeatureStatus.COMPLETED:
                completed_items.append(ctx)
            elif ctx.status == FeatureStatus.IN_PROGRESS:
                inprogress_items.append(ctx)
            else:
                backlog_items.append(ctx)

    # Generate dashboard content
    content = _generate_dashboard_content(
        backlog_items, inprogress_items, completed_items
    )

    # Write dashboard
    dashboard_path.write_text(content, encoding="utf-8")

    # Log to stderr (for hook feedback)
    print(f"[dashboard] Generated DASHBOARD.md with:", file=sys.stderr)
    print(f"  - {len(inprogress_items)} in progress", file=sys.stderr)
    print(f"  - {len(backlog_items)} in backlog", file=sys.stderr)
    print(f"  - {len(completed_items)} completed", file=sys.stderr)


def _generate_dashboard_content(
    backlog: list[FeatureContext],
    in_progress: list[FeatureContext],
    completed: list[FeatureContext],
) -> str:
    """Generate the markdown content for DASHBOARD.md."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        "# Feature Dashboard",
        "",
        "*Auto-generated by hooks. Do not edit directly.*",
        f"*Last updated: {timestamp}*",
        "",
        "## In Progress",
    ]

    if not in_progress:
        lines.append("*No features in progress*")
    else:
        lines.append("")
        lines.append("| ID | Name | Category | Priority | Started |")
        lines.append("|----|------|----------|----------|---------|")
        for ctx in in_progress:
            started = _format_date(ctx.started)
            lines.append(f"| [{ctx.feature_id}](./{ctx.feature_id}/) | {ctx.name} | {ctx.category} | {ctx.priority} | {started} |")

    lines.extend(["", "## Backlog"])

    if not backlog:
        lines.append("*No features in backlog*")
    else:
        lines.append("")
        lines.append("| ID | Name | Category | Priority | Effort | Added |")
        lines.append("|----|------|----------|----------|--------|-------|")
        for ctx in backlog:
            created = _format_date(ctx.created)
            lines.append(f"| [{ctx.feature_id}](./{ctx.feature_id}/) | {ctx.name} | {ctx.category} | {ctx.priority} | {ctx.effort} | {created} |")

    lines.extend(["", "## Completed"])

    if not completed:
        lines.append("*No completed features*")
    else:
        lines.append("")
        lines.append("| ID | Name | Shipped |")
        lines.append("|----|------|---------|")
        for ctx in completed:
            shipped = _format_date(ctx.shipped)
            lines.append(f"| [{ctx.feature_id}](./{ctx.feature_id}/) | {ctx.name} | {shipped} |")

    # Add trailing newline
    lines.append("")

    return "\n".join(lines)


def _format_date(d: Optional[object]) -> str:
    """Format a date for display, handling None values."""
    if d is None:
        return ""
    return str(d)


def main() -> int:
    """CLI entry point."""
    if len(sys.argv) < 2:
        print("Usage: python3 dashboard.py <project_root>", file=sys.stderr)
        return 1

    project_root = Path(sys.argv[1])

    if not project_root.is_dir():
        print(f"Error: {project_root} is not a directory", file=sys.stderr)
        return 1

    try:
        generate_dashboard(project_root)
        return 0
    except Exception as e:
        print(f"Error generating dashboard: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
