"""Tests for dashboard generation."""

from pathlib import Path

import pytest

# Import from the run_dashboard module since it has the standalone-compatible imports
import sys
LIB_DIR = Path(__file__).parent.parent / "lib"
if str(LIB_DIR) not in sys.path:
    sys.path.insert(0, str(LIB_DIR))

from run_dashboard import generate_dashboard


class TestGenerateDashboard:
    """Tests for generate_dashboard function."""

    def test_empty_project(self, temp_project: Path):
        """Test generating dashboard for empty project."""
        generate_dashboard(temp_project)

        dashboard_path = temp_project / "docs" / "features" / "DASHBOARD.md"
        assert dashboard_path.exists()

        content = dashboard_path.read_text()
        assert "# Feature Dashboard" in content
        assert "*No features in progress*" in content
        assert "*No features in backlog*" in content
        assert "*No completed features*" in content

    def test_single_backlog_feature(self, feature_in_backlog: Path):
        """Test dashboard with one backlog feature."""
        project_root = feature_in_backlog.parent.parent.parent
        generate_dashboard(project_root)

        dashboard_path = project_root / "docs" / "features" / "DASHBOARD.md"
        content = dashboard_path.read_text()

        assert "## Backlog" in content
        assert "test-feature" in content
        assert "Test Feature" in content
        assert "P1" in content
        assert "*No features in progress*" in content

    def test_single_in_progress_feature(self, feature_in_progress: Path):
        """Test dashboard with one in-progress feature."""
        project_root = feature_in_progress.parent.parent.parent
        generate_dashboard(project_root)

        dashboard_path = project_root / "docs" / "features" / "DASHBOARD.md"
        content = dashboard_path.read_text()

        assert "## In Progress" in content
        assert "test-feature" in content
        assert "*No features in backlog*" in content

    def test_single_completed_feature(self, feature_completed: Path):
        """Test dashboard with one completed feature."""
        project_root = feature_completed.parent.parent.parent
        generate_dashboard(project_root)

        dashboard_path = project_root / "docs" / "features" / "DASHBOARD.md"
        content = dashboard_path.read_text()

        assert "## Completed" in content
        assert "test-feature" in content
        assert "2024-01-25" in content

    def test_multiple_features(self, multiple_features: Path):
        """Test dashboard with features in all states."""
        generate_dashboard(multiple_features)

        dashboard_path = multiple_features / "docs" / "features" / "DASHBOARD.md"
        content = dashboard_path.read_text()

        # Check all sections have content
        assert "## In Progress" in content
        assert "progress-feature" in content

        assert "## Backlog" in content
        assert "backlog-feature" in content

        assert "## Completed" in content
        assert "done-feature" in content

    def test_creates_features_directory(self, tmp_path: Path):
        """Test that generate_dashboard creates docs/features if needed."""
        generate_dashboard(tmp_path)

        features_dir = tmp_path / "docs" / "features"
        assert features_dir.exists()

        dashboard_path = features_dir / "DASHBOARD.md"
        assert dashboard_path.exists()

    def test_dashboard_header(self, temp_project: Path):
        """Test dashboard has correct header."""
        generate_dashboard(temp_project)

        dashboard_path = temp_project / "docs" / "features" / "DASHBOARD.md"
        content = dashboard_path.read_text()

        assert content.startswith("# Feature Dashboard\n")
        assert "*Auto-generated by hooks. Do not edit directly.*" in content
        assert "*Last updated:" in content

    def test_table_format(self, feature_in_backlog: Path):
        """Test that tables are properly formatted."""
        project_root = feature_in_backlog.parent.parent.parent
        generate_dashboard(project_root)

        dashboard_path = project_root / "docs" / "features" / "DASHBOARD.md"
        content = dashboard_path.read_text()

        # Check backlog table headers
        assert "| ID | Name | Category | Priority | Effort | Added |" in content
        assert "|----|------|----------|----------|--------|-------|" in content

    def test_feature_links(self, feature_in_backlog: Path):
        """Test that feature IDs are links to directories."""
        project_root = feature_in_backlog.parent.parent.parent
        generate_dashboard(project_root)

        dashboard_path = project_root / "docs" / "features" / "DASHBOARD.md"
        content = dashboard_path.read_text()

        # Check that ID is a link
        assert "[test-feature](./test-feature/)" in content

    def test_backlog_table_includes_category(self, feature_in_backlog: Path):
        """Test that backlog table includes Category column."""
        project_root = feature_in_backlog.parent.parent.parent
        generate_dashboard(project_root)

        dashboard_path = project_root / "docs" / "features" / "DASHBOARD.md"
        content = dashboard_path.read_text()

        assert "| ID | Name | Category |" in content
        assert "| general |" in content or "general" in content

    def test_in_progress_table_includes_category(self, feature_in_progress: Path):
        """Test that in-progress table includes Category column."""
        project_root = feature_in_progress.parent.parent.parent
        generate_dashboard(project_root)

        dashboard_path = project_root / "docs" / "features" / "DASHBOARD.md"
        content = dashboard_path.read_text()

        # Check that the in-progress table header has Category
        lines = content.split("\n")
        for line in lines:
            if "| ID | Name | Category | Priority | Started |" in line:
                break
        else:
            pytest.fail("In Progress table missing Category column header")

    def test_skips_non_feature_directories(self, temp_project: Path):
        """Test that directories without idea.md are skipped."""
        features_dir = temp_project / "docs" / "features"

        # Create a non-feature directory
        (features_dir / "random-dir").mkdir()
        (features_dir / "random-dir" / "some-file.txt").write_text("not a feature")

        # Create a valid feature
        feature_dir = features_dir / "valid-feature"
        feature_dir.mkdir()
        (feature_dir / "idea.md").write_text("""---
name: Valid Feature
priority: P1
---
""")

        generate_dashboard(temp_project)

        dashboard_path = features_dir / "DASHBOARD.md"
        content = dashboard_path.read_text()

        assert "valid-feature" in content
        assert "random-dir" not in content
