#!/usr/bin/env python3
"""Initialize feature-workflow directory structure.

Usage:
    python3 init.py [project-root]

Creates:
    docs/features/
    docs/features/DASHBOARD.md (initial template)
"""

import sys
from pathlib import Path


INITIAL_DASHBOARD = """# Feature Dashboard

*Auto-generated by hooks. Do not edit directly.*

## In Progress

*No features in progress*

## Backlog

*No features in backlog. Use `/feature-capture` to add one.*

## Completed

*No completed features*
"""


def main() -> int:
    project_root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.cwd()
    features_dir = project_root / "docs" / "features"

    # Check if already initialized
    if features_dir.is_dir():
        print(f"Feature workflow already initialized at {features_dir}")

        # Count existing features
        feature_count = sum(1 for p in features_dir.iterdir() if p.is_dir())

        if (features_dir / "DASHBOARD.md").exists():
            print("DASHBOARD.md exists")

        print(f"Found {feature_count} feature directories")
        return 0

    # Create directory structure
    print("Initializing feature-workflow...")
    features_dir.mkdir(parents=True, exist_ok=True)

    # Create initial DASHBOARD.md
    dashboard_path = features_dir / "DASHBOARD.md"
    dashboard_path.write_text(INITIAL_DASHBOARD)

    print("")
    print("Feature workflow initialized!")
    print("")
    print(f"Directory: {features_dir}")
    print("")
    print("Next steps:")
    print("  /feature-capture  - Add a feature to the backlog")
    print("  /feature-plan     - Start implementing a feature")
    print("  /feature-ship     - Complete a feature")
    print("")

    return 0


if __name__ == "__main__":
    sys.exit(main())
